apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd

spec:
  description: Projeto ArgoCD para workloads do ambiente de desenvolvimento

  sourceRepos:
    - "https://github.com/Pbarbosa4410/gitops-argocd-kubernetes.git"

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  orphanedResources:
    warn: true